name: DemoWebshop Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install and Start WebDriver Manager
        run: |
            npm install webdriver-manager
            npx webdriver-manager update --gecko false
            npx webdriver-manager start --gecko false &
            sleep 5

      - name: Run Selenium Tests with Mochawesome
        run: |
            npm test -- --reporter mochawesome --reporter-options reportFilename=selenium

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
            name: mochawesome-report
            path: mochawesome-report/